-- V1 — initial schema.
--
-- Multi-user foundation (ADR-005): the `users` table and per-user ownership are
-- part of the project from day one, before any business entity exists. This is
-- the up-front multi-user decision made concrete — not a later toggle.

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Index that future per-user data scoping will rely on (owner lookups).
CREATE INDEX idx_users_username ON users (username);
