-- V2 — Ticket
-- THRAKSHA-OWNED — regenerated on every run.
-- Table for the Ticket entity. Columns match the model's fields.
-- Multi-user (ADR-005): owner_id ties each row to its owning user.

CREATE TABLE tickets (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    code VARCHAR(255),
    priority INTEGER,
    done BOOLEAN,
    owner_id    BIGINT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX ux_tickets_code ON tickets (code);

CREATE INDEX idx_tickets_owner_id ON tickets (owner_id);
