/*
 * Thraksha — PostgreSQL database provider.
 *
 * The first (and, until Day 5b, only) DatabaseProvider. It holds every
 * Postgres-specific string that used to be hardcoded across the four backend
 * plugins — the SQL dialect (types, identity, timestamps, FK/index), the users
 * and schema_migrations DDL, the driver dependencies, the connection URLs/engine,
 * and the Docker image. Extracted verbatim: this provider returns the exact
 * strings the backends produced before, so Postgres output stays byte-identical.
 */

import type { DatabaseProvider } from '../../core/database.js';

const SUPPORTED_TYPES = 'String, Text, Integer, Long, Decimal, Boolean, Date, DateTime';

/** The users-table DDL (shared by Spring/Express/FastAPI V1 migrations), verbatim. */
const USERS_TABLE_DDL = [
  'CREATE TABLE users (',
  '    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,',
  '    username      VARCHAR(100) NOT NULL UNIQUE,',
  '    password_hash VARCHAR(255) NOT NULL,',
  '    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,',
  '    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),',
  '    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()',
  ');',
].join('\n');

// The docker-compose `db` service's dialect-specific fragments. These reference
// the shell's project tokens (__DB_NAME__/__DB_USER__/__DB_PASSWORD__), which the
// backend resolves after the provider tokens (see the substitution note in
// core/database.ts). Extracted verbatim: Postgres output stays byte-identical.
const COMPOSE_DB_ENV = [
  'POSTGRES_DB: __DB_NAME__',
  '      POSTGRES_USER: __DB_USER__',
  '      POSTGRES_PASSWORD: __DB_PASSWORD__',
].join('\n');
const COMPOSE_HEALTHCHECK = '["CMD-SHELL", "pg_isready -U __DB_USER__ -d __DB_NAME__"]';

export const postgresProvider: DatabaseProvider = {
  id: 'postgres',
  displayName: 'PostgreSQL',

  // Postgres supports INSERT/UPDATE … RETURNING, so hand-SQL backends read the
  // affected row back in one statement.
  runtime: { supportsReturning: true },

  sql: {
    columnType(logicalType, opts) {
      switch (logicalType) {
        case 'String':
          return `VARCHAR(${opts?.maxLength ?? 255})`;
        case 'Text':
          return 'TEXT';
        case 'Integer':
          return 'INTEGER';
        case 'Long':
          return 'BIGINT';
        case 'Decimal':
          return 'NUMERIC(19, 2)';
        case 'Boolean':
          return 'BOOLEAN';
        case 'Date':
          return 'DATE';
        case 'DateTime':
          return 'TIMESTAMPTZ';
        default:
          throw new Error(`Unsupported field type "${logicalType}". INTAKE-SPEC supports: ${SUPPORTED_TYPES}.`);
      }
    },
    identityPrimaryKey: () => 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
    bigInt: () => 'BIGINT',
    timestampDefaultNow: () => 'TIMESTAMPTZ NOT NULL DEFAULT now()',
    foreignKey: (table, name, column, refTable) =>
      `ALTER TABLE ${table} ADD CONSTRAINT ${name} FOREIGN KEY (${column}) REFERENCES ${refTable} (id);`,
    index: (name, table, column, unique) =>
      `CREATE ${unique ? 'UNIQUE ' : ''}INDEX ${name} ON ${table} (${column});`,
  },

  tokens: () => ({
    // Docker
    __DB_IMAGE__: 'postgres:16-alpine',
    __DB_PORT__: '5432',
    __DB_VOLUME_PATH__: '/var/lib/postgresql/data',
    __DB_COMPOSE_DB_ENV__: COMPOSE_DB_ENV,
    __DB_COMPOSE_HEALTHCHECK__: COMPOSE_HEALTHCHECK,
    // Human-readable database name (README / comments prose)
    __DB_DISPLAY_NAME__: 'PostgreSQL',
    // DDL fragments (shell V1 users table + migrate-runner bookkeeping timestamp)
    __DB_USERS_TABLE_DDL__: USERS_TABLE_DDL,
    __DB_SCHEMA_MIGRATIONS_TS__: 'TIMESTAMPTZ NOT NULL DEFAULT now()',
    // Drivers / connection — Node (Express)
    __DB_NODE_DRIVER__: 'pg',
    __DB_NODE_DRIVER_VERSION__: '8.13.1',
    // Python — FastAPI (SQLAlchemy) and Django use different drivers on some
    // dialects, so they are separate tokens (identical here for Postgres).
    __DB_PY_DRIVER__: 'psycopg2-binary==2.9.10',
    __DB_SQLALCHEMY_URL_SCHEME__: 'postgresql+psycopg2',
    __DB_DJANGO_DRIVER__: 'psycopg2-binary==2.9.10',
    __DB_DJANGO_ENGINE__: 'django.db.backends.postgresql',
    // Java (Spring)
    __DB_JDBC_SCHEME__: 'jdbc:postgresql',
    __DB_JDBC_GROUP__: 'org.postgresql',
    __DB_JDBC_ARTIFACT__: 'postgresql',
    __DB_FLYWAY_ARTIFACT__: 'flyway-database-postgresql',
    // Go (database/sql): driver import path + registered driver name + go.mod
    // require line + DSN format (args: user, password, host, port, database).
    __DB_GO_DRIVER_IMPORT__: 'github.com/lib/pq',
    __DB_GO_DRIVER_NAME__: 'postgres',
    __DB_GO_DRIVER_REQUIRE__: 'github.com/lib/pq v1.10.9',
    __DB_GO_DSN_FORMAT__: 'postgres://%s:%s@%s:%s/%s?sslmode=disable',
    // Positional placeholders for hand-written shell SQL (Go): $N for Postgres.
    __DB_PH1__: '$1',
    __DB_PH2__: '$2',
  }),
};
